version: "3.8"
services:
  db:
    image: mysql:8
    restart: always # Tự động khởi động lại nếu container dừng
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore-ca
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  db_data: